### ISSUE TITLE
 About feature Cache

### ISSUE THREAD

**Issue by fty2000** [Rex-sys-hk/PlanScope#3]
Hello, thank you for your great work.My hard disk space currently cannot support feature caching operations. If it is convenient for you, can you share the feature cached files? If necessary, I can provide my Alibaba Cloud Disk（阿里云盘） and Quark Network Disk （夸克网盘）accounts, which have sufficient space. It is difficult for me to use Google Drive in mainland China. Thanks a lot anyway.

**Comment by Rex-sys-hk** [comment]
We strongly recommend that you preprocess the data yourself, because the original data is still needed in the evaluation stage. In addition, direct copying the cache might cause unexpected problems. If you still need my help, please contact me by email(rxin@connect.ust.hk) for further communication.

**Comment by fty2000** [comment]
Thank you a lot!I will contact you later.
